name: 'test'

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.1]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          always-auth: true
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint
